import 'dart:async';

import 'package:apk_arena/models/level_outcome.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../theme/app_theme.dart';
import '../level_components/level_hud.dart';
import '../level_widget.dart';

/// Ricochet-robots campaign: eight hardcoded boards, gated progression,
/// internal budget starting at 15:00 with +3:00 after each solved board.
///
/// Robots slide until they hit a wall edge or another robot — no partial
/// moves. Swipe on a robot to slide it. Reaching the ring at par (the BFS
/// optimum) clears the stage at full value; over par the player may bank
/// the stage for (par/moves)^2 credit, so sloppy lines are worth little.
/// Undo and reset are free.
///
/// Every board was generated and BFS-verified by `ricochet_gen.py` with
/// these exact sliding rules. From stage 3 on the target robot provably
/// cannot reach the ring on its own (solo BFS exhausts), and the verified
/// optimal line contains 1-6 crash-stops — moves that end by ramming
/// another robot in open field. Do not edit a board without re-verifying.
class LevelRicochetLab extends LevelWidget {
  const LevelRicochetLab({super.key, required super.onComplete});

  @override
  State<LevelRicochetLab> createState() => _LevelRicochetLabState();
}

class _RicochetBoard {
  final int size;

  /// One hex digit per cell: wall bitmask N=1, E=2, S=4, W=8.
  final List<String> wallRows;
  final List<int> robotCells;
  final int targetRobot;
  final int targetCell;
  final int optimalMoves;

  const _RicochetBoard({
    required this.size,
    required this.wallRows,
    required this.robotCells,
    required this.targetRobot,
    required this.targetCell,
    required this.optimalMoves,
  });
}

class _LevelRicochetLabState extends State<LevelRicochetLab> {
  static const int _stageCount = 8;
  static const Duration _initialBudget = Duration(minutes: 15);
  static const Duration _bonusPerStage = Duration(minutes: 3);

  static const List<Color> _robotColors = [
    Color(0xFFE55CD8), // pink
    Color(0xFF805CE5), // purple
    Color(0xFF22D3EE), // cyan
    Color(0xFFFFAB00), // amber
  ];
  static const List<String> _robotNames = ['pink', 'purple', 'cyan', 'amber'];

  // generated by ricochet_gen.py — BFS-verified, do not hand-edit
  static const List<_RicochetBoard> _boards = [
    // stage 1: optimal 3, target robot purple, crash-stops in optimal line: 1
    _RicochetBoard(
      size: 10,
      wallRows: [
        '9151111113',
        '8290000002',
        '8000000002',
        '80002c0682',
        '8000050102',
        '8000290002',
        '8006c042c2',
        '8003903ad2',
        '8000000012',
        'c444444446',
      ],
      robotCells: [88, 4, 28, 64],
      targetRobot: 1,
      targetCell: 70,
      optimalMoves: 3,
    ),
    // stage 2: optimal 5, target robot purple, crash-stops in optimal line: 2
    _RicochetBoard(
      size: 10,
      wallRows: [
        '9115111113',
        '8029000002',
        '8000000002',
        '8000000002',
        '8000680002',
        '8046900682',
        'ae9100016a',
        '83c2c02c12',
        '8010100102',
        'c444444446',
      ],
      robotCells: [46, 93, 47, 5],
      targetRobot: 1,
      targetCell: 49,
      optimalMoves: 5,
    ),
    // stage 3: optimal 7, target robot amber, crash-stops in optimal line: 2
    _RicochetBoard(
      size: 11,
      wallRows: [
        '91111111113',
        '80004000002',
        '8402900686a',
        'a9000001012',
        '84000000002',
        'a9000400402',
        '80000382fc2',
        '80000000392',
        'ac000002c02',
        '8100002c102',
        'c4444445446',
      ],
      robotCells: [41, 114, 44, 42],
      targetRobot: 3,
      targetCell: 85,
      optimalMoves: 7,
    ),
    // stage 4: optimal 8, target robot pink, crash-stops in optimal line: 3
    _RicochetBoard(
      size: 11,
      wallRows: [
        '91111111113',
        '8000002c002',
        '80000005002',
        '80000003802',
        '80400004002',
        '803c0003802',
        'ac2f802c002',
        'ad010001002',
        '81068000002',
        '82c10680002',
        'c4544544446',
      ],
      robotCells: [114, 90, 32, 120],
      targetRobot: 0,
      targetCell: 113,
      optimalMoves: 8,
    ),
    // stage 5: optimal 9, target robot amber, crash-stops in optimal line: 3
    _RicochetBoard(
      size: 12,
      wallRows: [
        '915111111113',
        '829468680002',
        '800390100002',
        '800400000402',
        '802900002902',
        '8002c0000002',
        '8000102c0002',
        '80040001006a',
        'ac0380004012',
        '810004003842',
        '800003800292',
        'c44444444446',
      ],
      robotCells: [111, 131, 89, 15],
      targetRobot: 3,
      targetCell: 129,
      optimalMoves: 9,
    ),
    // stage 6: optimal 10, target robot amber, crash-stops in optimal line: 4
    _RicochetBoard(
      size: 12,
      wallRows: [
        '911111115113',
        '800400029002',
        '800380000002',
        '82c02c000002',
        '801401000002',
        '800384000002',
        '840003800002',
        'a92c00002c42',
        '8003c000413a',
        '800050429002',
        '80003a900002',
        'c44444444446',
      ],
      robotCells: [53, 71, 83, 54],
      targetRobot: 3,
      targetCell: 26,
      optimalMoves: 10,
    ),
    // stage 7: optimal 11, target robot pink, crash-stops in optimal line: 5
    _RicochetBoard(
      size: 12,
      wallRows: [
        '911115111113',
        '840029000002',
        '83e802c00002',
        '805040100402',
        '803838002902',
        '800000000002',
        '800680000002',
        '8005402c0002',
        '82eb90010002',
        '805068000002',
        '803816800002',
        'c44445444446',
      ],
      robotCells: [66, 84, 96, 57],
      targetRobot: 0,
      targetCell: 92,
      optimalMoves: 11,
    ),
    // stage 8: optimal 12, target robot amber, crash-stops in optimal line: 6
    _RicochetBoard(
      size: 12,
      wallRows: [
        '911511115113',
        '802f80683c02',
        '86c100102902',
        '83d000000002',
        '8038002c0002',
        'ac4004010002',
        '813829000002',
        '840000000002',
        '838000000002',
        '840000000002',
        'a90000000682',
        'c44444444546',
      ],
      robotCells: [20, 97, 66, 77],
      targetRobot: 3,
      targetCell: 115,
      optimalMoves: 12,
    ),
  ];

  static const List<List<int>> _deltas = [
    [-1, 0], // N
    [0, 1], // E
    [1, 0], // S
    [0, -1], // W
  ];
  static const List<int> _dirBits = [1, 2, 4, 8];

  late _RicochetBoard _board;
  late List<List<int>> _walls;
  late List<int> _robots; // cell index per robot
  int _stageIndex = 0;
  int _stageMoves = 0;
  int _secondsRemaining = _initialBudget.inSeconds;
  Timer? _budgetTimer;
  bool _runFinished = false;

  int _dragRobot = -1;
  Offset _dragDelta = Offset.zero;

  int _totalMoves = 0;
  int _parSolves = 0;
  final List<double> _stageCredits = [];
  final List<List<int>> _history = [];

  @override
  void initState() {
    super.initState();
    widget.registerPartialScoreGetter(_buildPartialOutcome);
    _loadStage(_stageIndex);
    _startBudgetTimer();
  }

  @override
  void dispose() {
    _budgetTimer?.cancel();
    widget.clearPartialScoreGetter();
    super.dispose();
  }

  double get _currentScore {
    final total = _stageCredits.fold<double>(0, (a, b) => a + b);
    return total / _stageCount;
  }

  LevelOutcome _buildPartialOutcome() {
    return LevelOutcome(
      score: _currentScore,
      metrics: {
        'stages_cleared': _stageCredits.length,
        'par_solves': _parSolves,
        'moves': _totalMoves,
      },
    );
  }

  String _formatTime(int seconds) {
    final safe = seconds.clamp(0, 99999);
    final m = (safe ~/ 60).toString().padLeft(2, '0');
    final s = (safe % 60).toString().padLeft(2, '0');
    return '$m:$s';
  }

  void _startBudgetTimer() {
    _budgetTimer?.cancel();
    _budgetTimer = Timer.periodic(const Duration(seconds: 1), (_) {
      if (!mounted || _runFinished) return;
      setState(() {
        if (_secondsRemaining <= 0) return;
        _secondsRemaining--;
        if (_secondsRemaining <= 0) {
          _failRun();
        }
      });
    });
  }

  void _loadStage(int index) {
    _board = _boards[index];
    _walls = List.generate(
      _board.size,
      (r) => List.generate(
        _board.size,
        (c) => int.parse(_board.wallRows[r][c], radix: 16),
      ),
    );
    _robots = List<int>.from(_board.robotCells);
    _stageMoves = 0;
    _history.clear();
  }

  /// Destination cell for sliding [robot] in direction [dir]; may equal the
  /// current cell (illegal move). Must match ricochet_gen.py exactly.
  int _slideDest(int robot, int dir) {
    final size = _board.size;
    var r = _robots[robot] ~/ size;
    var c = _robots[robot] % size;
    final occupied = <int>{
      for (var i = 0; i < _robots.length; i++)
        if (i != robot) _robots[i],
    };
    while (true) {
      if (_walls[r][c] & _dirBits[dir] != 0) break;
      final nr = r + _deltas[dir][0];
      final nc = c + _deltas[dir][1];
      if (occupied.contains(nr * size + nc)) break;
      r = nr;
      c = nc;
    }
    return r * size + c;
  }

  void _slide(int robot, int dir) {
    if (_runFinished) return;
    final dest = _slideDest(robot, dir);
    if (dest == _robots[robot]) return;
    setState(() {
      _history.add(List<int>.from(_robots));
      _robots[robot] = dest;
      _stageMoves++;
      _totalMoves++;
      HapticFeedback.selectionClick();
      if (_robots[_board.targetRobot] == _board.targetCell) {
        if (_stageMoves <= _board.optimalMoves) {
          _onStageCleared(1.0, atPar: true);
        } else {
          HapticFeedback.heavyImpact();
        }
      }
    });
  }

  void _undo() {
    if (_runFinished || _history.isEmpty) return;
    setState(() {
      _robots = _history.removeLast();
      _stageMoves--;
      _totalMoves--;
    });
  }

  void _resetCurrentStage() {
    if (_runFinished) return;
    HapticFeedback.selectionClick();
    setState(() => _loadStage(_stageIndex));
  }

  /// Credit for banking the current over-par position; quadratic falloff so
  /// sloppy solutions are worth little (par 8 in 10 moves -> 0.64).
  double get _bankCredit {
    final ratio = _board.optimalMoves / _stageMoves;
    return (ratio * ratio).clamp(0.0, 1.0);
  }

  bool get _onRing => _robots[_board.targetRobot] == _board.targetCell;

  void _bankStage() {
    if (_runFinished || !_onRing || _stageMoves <= _board.optimalMoves) return;
    _onStageCleared(_bankCredit, atPar: false);
  }

  void _onStageCleared(double credit, {required bool atPar}) {
    _stageCredits.add(credit);
    if (atPar) _parSolves++;
    HapticFeedback.mediumImpact();

    if (_stageIndex >= _stageCount - 1) {
      _finishRun();
      return;
    }
    _secondsRemaining += _bonusPerStage.inSeconds;
    _stageIndex++;
    _loadStage(_stageIndex);
  }

  void _finishRun() {
    if (_runFinished) return;
    _runFinished = true;
    _budgetTimer?.cancel();
    Future.delayed(const Duration(milliseconds: 400), () {
      if (!mounted) return;
      widget.onComplete(
        LevelOutcome(
          score: _currentScore,
          metrics: {
            'stages_cleared': _stageCredits.length,
            'par_solves': _parSolves,
            'moves': _totalMoves,
            'seconds_left': _secondsRemaining,
          },
        ),
      );
    });
  }

  void _failRun() {
    if (_runFinished) return;
    _runFinished = true;
    _budgetTimer?.cancel();
    Future.delayed(const Duration(milliseconds: 300), () {
      if (!mounted) return;
      widget.onComplete(
        LevelOutcome(
          score: _currentScore,
          metrics: {
            'stages_cleared': _stageCredits.length,
            'par_solves': _parSolves,
            'timed_out': true,
            'moves': _totalMoves,
          },
        ),
      );
    });
  }

  void _onPanStart(Offset local, double cellSize) {
    final size = _board.size;
    final c = (local.dx / cellSize).floor().clamp(0, size - 1);
    final r = (local.dy / cellSize).floor().clamp(0, size - 1);
    final cell = r * size + c;
    _dragRobot = _robots.indexOf(cell);
    _dragDelta = Offset.zero;
  }

  void _onPanEnd() {
    if (_dragRobot == -1) return;
    final d = _dragDelta;
    _dragDelta = Offset.zero;
    if (d.distance < 20) {
      _dragRobot = -1;
      return;
    }
    final int dir;
    if (d.dx.abs() >= d.dy.abs()) {
      dir = d.dx > 0 ? 1 : 3;
    } else {
      dir = d.dy > 0 ? 2 : 0;
    }
    final robot = _dragRobot;
    _dragRobot = -1;
    _slide(robot, dir);
  }

  @override
  Widget build(BuildContext context) {
    final targetColor = _robotColors[_board.targetRobot];
    return Container(
      color: NunuColors.backgroundDefault,
      child: SafeArea(
        child: Column(
          children: [
            LevelHud(
              timerText: _formatTime(_secondsRemaining),
              stageText: '${_stageIndex + 1}/$_stageCount',
              infoTitle: 'ricochet lab',
              infoItems: const [
                LevelHudBullet('🤖', 'swipe on a robot to slide it. robots slide until they hit a wall or another robot — no partial moves'),
                LevelHudBullet('🎯', 'get the marked robot onto the ring of its color. any robot may be moved — parked robots make good anchors'),
                LevelHudBullet('⭐', 'reaching the ring at par clears the stage at full value. over par you may bank the stage for reduced credit — the further over par, the less it\'s worth'),
                LevelHudBullet('⏱', 'you start with 15:00 and earn +3:00 for each stage cleared'),
              ],
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Flexible(
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Container(
                          width: 14,
                          height: 14,
                          decoration: BoxDecoration(
                            color: targetColor,
                            shape: BoxShape.circle,
                          ),
                        ),
                        const SizedBox(width: 6),
                        Flexible(
                          child: Text(
                            '${_robotNames[_board.targetRobot]} to the ring',
                            overflow: TextOverflow.ellipsis,
                            style: const TextStyle(
                              color: NunuColors.textSecondary,
                              fontSize: 13,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 8),
                  Text(
                    'moves: $_stageMoves / par ${_board.optimalMoves}',
                    style: TextStyle(
                      color: _stageMoves > _board.optimalMoves
                          ? NunuColors.errorMain
                          : NunuColors.textSecondary,
                      fontSize: 13,
                      fontWeight: FontWeight.w700,
                      fontFeatures: const [FontFeature.tabularFigures()],
                    ),
                  ),
                ],
              ),
            ),
            if (_onRing && _stageMoves > _board.optimalMoves)
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Container(
                  width: double.infinity,
                  padding: const EdgeInsets.symmetric(
                    horizontal: 14,
                    vertical: 10,
                  ),
                  decoration: BoxDecoration(
                    color: NunuColors.warningMain.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                      color: NunuColors.warningMain.withValues(alpha: 0.7),
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'ring reached in $_stageMoves — over par '
                        '(${_board.optimalMoves}). undo/reset for full value, '
                        'or bank it now.',
                        style: const TextStyle(
                          color: NunuColors.warningMain,
                          fontSize: 13,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Material(
                        color: NunuColors.warningMain.withValues(alpha: 0.2),
                        borderRadius: BorderRadius.circular(8),
                        child: InkWell(
                          borderRadius: BorderRadius.circular(8),
                          onTap: _bankStage,
                          child: Padding(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 14,
                              vertical: 8,
                            ),
                            child: Text(
                              'bank stage for ${(_bankCredit * 100).round()}%',
                              style: const TextStyle(
                                color: NunuColors.warningMain,
                                fontSize: 13,
                                fontWeight: FontWeight.w800,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            Expanded(child: Center(child: _buildBoard())),
            const SizedBox(height: 4),
            _buildControls(),
            const SizedBox(height: 8),
          ],
        ),
      ),
    );
  }

  Widget _buildBoard() {
    return LayoutBuilder(
      builder: (context, constraints) {
        final size = _board.size;
        final boardSide =
            (constraints.maxWidth - 16).clamp(0.0, constraints.maxHeight);
        final cellSize = boardSide / size;

        return SizedBox(
          width: boardSide,
          height: boardSide,
          child: GestureDetector(
            onPanStart: (d) => _onPanStart(d.localPosition, cellSize),
            onPanUpdate: (d) => _dragDelta += d.delta,
            onPanEnd: (_) => _onPanEnd(),
            child: Stack(
              children: [
                Positioned.fill(
                  child: CustomPaint(
                    painter: _BoardPainter(
                      size: size,
                      walls: _walls,
                      targetCell: _board.targetCell,
                      targetColor: _robotColors[_board.targetRobot],
                    ),
                  ),
                ),
                for (var i = 0; i < _robots.length; i++)
                  AnimatedPositioned(
                    duration: const Duration(milliseconds: 140),
                    curve: Curves.easeOutCubic,
                    left: (_robots[i] % size) * cellSize + cellSize * 0.14,
                    top: (_robots[i] ~/ size) * cellSize + cellSize * 0.14,
                    width: cellSize * 0.72,
                    height: cellSize * 0.72,
                    child: Container(
                      decoration: BoxDecoration(
                        color: _robotColors[i],
                        shape: BoxShape.circle,
                        border: Border.all(
                          color: i == _board.targetRobot
                              ? Colors.white
                              : Colors.white.withValues(alpha: 0.25),
                          width: i == _board.targetRobot ? 2.5 : 1,
                        ),
                        boxShadow: [
                          BoxShadow(
                            color: _robotColors[i].withValues(
                              alpha: i == _board.targetRobot ? 0.6 : 0.3,
                            ),
                            blurRadius: i == _board.targetRobot ? 8 : 4,
                          ),
                        ],
                      ),
                      child: Icon(
                        Icons.smart_toy,
                        color: Colors.white,
                        size: cellSize * 0.36,
                      ),
                    ),
                  ),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildControls() {
    Widget actionButton(IconData icon, String label, VoidCallback onTap) {
      return Material(
        color: NunuColors.backgroundPaper,
        borderRadius: BorderRadius.circular(12),
        child: InkWell(
          borderRadius: BorderRadius.circular(12),
          onTap: onTap,
          child: Container(
            height: 48,
            padding: const EdgeInsets.symmetric(horizontal: 20),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: NunuColors.secondaryDark.withValues(alpha: 0.55),
              ),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(icon, color: NunuColors.secondaryLight, size: 22),
                const SizedBox(width: 8),
                Text(
                  label,
                  style: const TextStyle(
                    color: NunuColors.secondaryLight,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    }

    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        actionButton(Icons.undo_rounded, 'undo', _undo),
        const SizedBox(width: 12),
        actionButton(Icons.refresh_rounded, 'reset', _resetCurrentStage),
      ],
    );
  }
}

class _BoardPainter extends CustomPainter {
  final int size;
  final List<List<int>> walls;
  final int targetCell;
  final Color targetColor;

  _BoardPainter({
    required this.size,
    required this.walls,
    required this.targetCell,
    required this.targetColor,
  });

  @override
  void paint(Canvas canvas, Size canvasSize) {
    final cell = canvasSize.width / size;

    final floorPaint = Paint()
      ..color = NunuColors.backgroundPaper.withValues(alpha: 0.72);
    canvas.drawRect(
      Rect.fromLTWH(0, 0, canvasSize.width, canvasSize.height),
      floorPaint,
    );

    final gridPaint = Paint()
      ..color = Colors.white.withValues(alpha: 0.07)
      ..strokeWidth = 1;
    for (var i = 1; i < size; i++) {
      canvas.drawLine(
        Offset(i * cell, 0),
        Offset(i * cell, canvasSize.height),
        gridPaint,
      );
      canvas.drawLine(
        Offset(0, i * cell),
        Offset(canvasSize.width, i * cell),
        gridPaint,
      );
    }

    // target ring
    final tr = targetCell ~/ size;
    final tc = targetCell % size;
    final center = Offset((tc + 0.5) * cell, (tr + 0.5) * cell);
    canvas.drawCircle(
      center,
      cell * 0.34,
      Paint()
        ..color = targetColor.withValues(alpha: 0.9)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 3,
    );
    canvas.drawCircle(
      center,
      cell * 0.34,
      Paint()..color = targetColor.withValues(alpha: 0.15),
    );

    final wallPaint = Paint()
      ..color = NunuColors.primaryLight
      ..strokeWidth = 4
      ..strokeCap = StrokeCap.round;
    for (var r = 0; r < size; r++) {
      for (var c = 0; c < size; c++) {
        final w = walls[r][c];
        final left = c * cell;
        final top = r * cell;
        if (w & 1 != 0) {
          canvas.drawLine(
            Offset(left, top),
            Offset(left + cell, top),
            wallPaint,
          );
        }
        if (w & 2 != 0) {
          canvas.drawLine(
            Offset(left + cell, top),
            Offset(left + cell, top + cell),
            wallPaint,
          );
        }
        if (w & 4 != 0) {
          canvas.drawLine(
            Offset(left, top + cell),
            Offset(left + cell, top + cell),
            wallPaint,
          );
        }
        if (w & 8 != 0) {
          canvas.drawLine(Offset(left, top), Offset(left, top + cell), wallPaint);
        }
      }
    }
  }

  @override
  bool shouldRepaint(_BoardPainter old) =>
      old.walls != walls || old.targetCell != targetCell || old.size != size;
}
