import 'dart:async';
import 'dart:ui' as ui;

import 'package:apk_arena/models/level_outcome.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../theme/app_theme.dart';
import '../level_components/level_hud.dart';
import '../level_widget.dart';

/// Sliding-picture campaign: five fixed scrambles from 3x3 up to 7x7, each a
/// different painting. Tiles carry image crops only — no numbers and no
/// reference picture — the solved arrangement must be inferred from the
/// tile contents alone. The full painting is only revealed on stage clear.
///
/// Internal budget starts at 15:00 with +8:00 after each solved stage.
/// Tapping any tile in the blank's row/column slides the whole segment;
/// every cell shifted counts as one move.
///
/// Scrambles were generated by `portrait_gen.py`: uniform permutations with
/// solvability enforced via the n-puzzle parity rule. The 3x3 par is the
/// exact IDA* optimum; larger pars are calibrated budgets for a competent
/// tile-by-tile solve. Do not edit a scramble without re-verifying parity.
class LevelShatteredPortrait extends LevelWidget {
  const LevelShatteredPortrait({super.key, required super.onComplete});

  @override
  State<LevelShatteredPortrait> createState() => _LevelShatteredPortraitState();
}

class _PortraitStage {
  final int n;
  final String asset;

  /// scramble[position] = tile id; blank tile id is n*n-1; solved = identity.
  final List<int> scramble;
  final int par;

  const _PortraitStage({
    required this.n,
    required this.asset,
    required this.scramble,
    required this.par,
  });
}

class _LevelShatteredPortraitState extends State<LevelShatteredPortrait> {
  static const int _stageCount = 5;
  static const Duration _initialBudget = Duration(minutes: 15);
  static const Duration _bonusPerStage = Duration(minutes: 8);

  // generated by portrait_gen.py — solvability parity-verified, do not hand-edit
  static const List<_PortraitStage> _stages = [
    // 3x3: par 27 (exact optimal)
    _PortraitStage(
      n: 3,
      asset: 'assets/generai_paintings/sunset.png',
      scramble: [7, 3, 6, 4, 2, 8, 1, 5, 0],
      par: 27,
    ),
    // 4x4: par 140 (move budget)
    _PortraitStage(
      n: 4,
      asset: 'assets/generai_paintings/fields.png',
      scramble: [6, 3, 1, 0, 9, 13, 8, 11, 7, 15, 12, 4, 14, 10, 2, 5],
      par: 140,
    ),
    // 5x5: par 320 (move budget)
    _PortraitStage(
      n: 5,
      asset: 'assets/generai_paintings/island.png',
      scramble: [
        11, 13, 7, 22, 15, 14, 16, 19, 23, 21, 17, 18, 3, 6, 1, 24, 12, 2,
        10, 9, 0, 20, 5, 8, 4,
      ],
      par: 320,
    ),
    // 6x6: par 620 (move budget)
    _PortraitStage(
      n: 6,
      asset: 'assets/generai_paintings/cactus.png',
      scramble: [
        6, 9, 33, 20, 22, 25, 13, 7, 28, 3, 21, 31, 30, 26, 34, 2, 10, 0,
        5, 15, 17, 16, 19, 8, 29, 23, 27, 14, 11, 12, 4, 1, 32, 35, 24, 18,
      ],
      par: 620,
    ),
    // 7x7: par 1050 (move budget)
    _PortraitStage(
      n: 7,
      asset: 'assets/generai_paintings/market.png',
      scramble: [
        0, 31, 9, 8, 24, 48, 42, 25, 15, 6, 34, 22, 12, 39, 23, 1, 13, 43,
        32, 5, 27, 10, 20, 46, 33, 47, 7, 16, 41, 11, 37, 4, 40, 30, 28, 2,
        21, 17, 38, 19, 14, 18, 36, 45, 26, 35, 29, 3, 44,
      ],
      par: 1050,
    ),
  ];

  late _PortraitStage _stage;
  late List<int> _perm;
  ui.Image? _image;
  int _stageIndex = 0;
  int _stageMoves = 0;
  int _secondsRemaining = _initialBudget.inSeconds;
  Timer? _budgetTimer;
  bool _runFinished = false;
  bool _stageSolvedPause = false;

  int _totalMoves = 0;
  final List<double> _stageCredits = [];

  @override
  void initState() {
    super.initState();
    widget.registerPartialScoreGetter(_buildPartialOutcome);
    _loadStage(_stageIndex);
    _startBudgetTimer();
  }

  @override
  void dispose() {
    _budgetTimer?.cancel();
    _image?.dispose();
    widget.clearPartialScoreGetter();
    super.dispose();
  }

  double get _currentScore {
    final total = _stageCredits.fold<double>(0, (a, b) => a + b);
    return total / _stageCount;
  }

  LevelOutcome _buildPartialOutcome() {
    return LevelOutcome(
      score: _currentScore,
      metrics: {'stages_cleared': _stageCredits.length, 'moves': _totalMoves},
    );
  }

  String _formatTime(int seconds) {
    final safe = seconds.clamp(0, 99999);
    final m = (safe ~/ 60).toString().padLeft(2, '0');
    final s = (safe % 60).toString().padLeft(2, '0');
    return '$m:$s';
  }

  void _startBudgetTimer() {
    _budgetTimer?.cancel();
    _budgetTimer = Timer.periodic(const Duration(seconds: 1), (_) {
      if (!mounted || _runFinished) return;
      setState(() {
        if (_secondsRemaining <= 0) return;
        _secondsRemaining--;
        if (_secondsRemaining <= 0) {
          _failRun();
        }
      });
    });
  }

  void _loadStage(int index) {
    _stage = _stages[index];
    _perm = List<int>.from(_stage.scramble);
    _stageMoves = 0;
    _stageSolvedPause = false;
    _loadImage(_stage.asset);
  }

  Future<void> _loadImage(String asset) async {
    _image?.dispose();
    _image = null;
    final data = await rootBundle.load(asset);
    final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
    final frame = await codec.getNextFrame();
    if (!mounted) {
      frame.image.dispose();
      return;
    }
    setState(() => _image = frame.image);
  }

  bool get _isSolved {
    for (var i = 0; i < _perm.length; i++) {
      if (_perm[i] != i) return false;
    }
    return true;
  }

  void _onCellTap(int r, int c) {
    if (_runFinished || _stageSolvedPause) return;
    final n = _stage.n;
    final blankPos = _perm.indexOf(n * n - 1);
    final br = blankPos ~/ n;
    final bc = blankPos % n;
    if (r == br && c == bc) return;
    if (r != br && c != bc) return;

    setState(() {
      // shift the whole segment between tapped cell and blank toward the blank
      var moved = 0;
      if (r == br) {
        final step = c < bc ? -1 : 1;
        var cur = bc;
        while (cur != c) {
          _perm[r * n + cur] = _perm[r * n + cur + step];
          cur += step;
          moved++;
        }
        _perm[r * n + c] = n * n - 1;
      } else {
        final step = r < br ? -1 : 1;
        var cur = br;
        while (cur != r) {
          _perm[cur * n + c] = _perm[(cur + step) * n + c];
          cur += step;
          moved++;
        }
        _perm[r * n + c] = n * n - 1;
      }
      _stageMoves += moved;
      _totalMoves += moved;
      HapticFeedback.selectionClick();
      if (_isSolved) {
        _onStageSolved();
      }
    });
  }

  void _onStageSolved() {
    final credit = (_stage.par / _stageMoves).clamp(0.5, 1.0).toDouble();
    _stageCredits.add(credit);
    _stageSolvedPause = true;
    HapticFeedback.mediumImpact();

    Future.delayed(const Duration(milliseconds: 1200), () {
      if (!mounted || _runFinished) return;
      if (_stageIndex >= _stageCount - 1) {
        _finishRun();
        return;
      }
      setState(() {
        _secondsRemaining += _bonusPerStage.inSeconds;
        _stageIndex++;
        _loadStage(_stageIndex);
      });
    });
  }

  void _resetCurrentStage() {
    if (_runFinished || _stageSolvedPause) return;
    HapticFeedback.selectionClick();
    setState(() {
      _perm = List<int>.from(_stage.scramble);
      _stageMoves = 0;
    });
  }

  void _finishRun() {
    if (_runFinished) return;
    _runFinished = true;
    _budgetTimer?.cancel();
    widget.onComplete(
      LevelOutcome(
        score: _currentScore,
        metrics: {
          'stages_cleared': _stageCredits.length,
          'moves': _totalMoves,
          'seconds_left': _secondsRemaining,
        },
      ),
    );
  }

  void _failRun() {
    if (_runFinished) return;
    _runFinished = true;
    _budgetTimer?.cancel();
    Future.delayed(const Duration(milliseconds: 300), () {
      if (!mounted) return;
      widget.onComplete(
        LevelOutcome(
          score: _currentScore,
          metrics: {
            'stages_cleared': _stageCredits.length,
            'timed_out': true,
            'moves': _totalMoves,
          },
        ),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: NunuColors.backgroundDefault,
      child: SafeArea(
        child: Column(
          children: [
            LevelHud(
              timerText: _formatTime(_secondsRemaining),
              stageText: '${_stageIndex + 1}/$_stageCount',
              infoTitle: 'shattered portrait',
              infoItems: const [
                LevelHudBullet('🖼', 'rebuild the painting from the shuffled tiles. there is no reference — read the picture from the pieces'),
                LevelHudBullet('👆', 'tap any tile in the empty cell\'s row or column to slide the whole segment'),
                LevelHudBullet('⭐', 'full credit needs the stage solved within par moves. reset is free'),
                LevelHudBullet('⏱', 'you start with 15:00 and earn +8:00 for each stage cleared'),
              ],
            ),
            _buildStatusRow(),
            Expanded(child: Center(child: _buildBoard())),
            const SizedBox(height: 8),
            _buildResetButton(),
            const SizedBox(height: 12),
          ],
        ),
      ),
    );
  }

  Widget _buildStatusRow() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          Text(
            'moves: $_stageMoves · par: ${_stage.par}',
            style: const TextStyle(
              color: NunuColors.textSecondary,
              fontSize: 13,
              fontWeight: FontWeight.w700,
              fontFeatures: [FontFeature.tabularFigures()],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBoard() {
    return LayoutBuilder(
      builder: (context, constraints) {
        final n = _stage.n;
        final side =
            (constraints.maxWidth - 16).clamp(0.0, constraints.maxHeight);
        final cellSize = side / n;

        if (_image == null) {
          return SizedBox(
            width: side,
            height: side,
            child: const Center(
              child: CircularProgressIndicator(color: NunuColors.primaryMain),
            ),
          );
        }

        return SizedBox(
          width: side,
          height: side,
          child: GestureDetector(
            onTapDown: (d) {
              final c = (d.localPosition.dx / cellSize).floor().clamp(0, n - 1);
              final r = (d.localPosition.dy / cellSize).floor().clamp(0, n - 1);
              _onCellTap(r, c);
            },
            child: CustomPaint(
              painter: _PuzzlePainter(
                image: _image!,
                n: n,
                perm: List<int>.of(_perm),
                solvedPause: _stageSolvedPause,
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildResetButton() {
    return SizedBox(
      height: 48,
      child: Material(
        color: NunuColors.backgroundPaper,
        borderRadius: BorderRadius.circular(12),
        child: InkWell(
          borderRadius: BorderRadius.circular(12),
          onTap: _resetCurrentStage,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 24),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: NunuColors.secondaryDark.withValues(alpha: 0.55),
              ),
            ),
            child: const Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  Icons.refresh_rounded,
                  color: NunuColors.secondaryLight,
                  size: 22,
                ),
                SizedBox(width: 8),
                Text(
                  'reset stage',
                  style: TextStyle(
                    color: NunuColors.secondaryLight,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

}

/// Centered-square crop of [image], as src rect in image pixels.
Rect _cropRect(ui.Image image) {
  final w = image.width.toDouble();
  final h = image.height.toDouble();
  final side = w < h ? w : h;
  return Rect.fromLTWH((w - side) / 2, (h - side) / 2, side, side);
}

class _PuzzlePainter extends CustomPainter {
  final ui.Image image;
  final int n;
  final List<int> perm;
  final bool solvedPause;

  _PuzzlePainter({
    required this.image,
    required this.n,
    required this.perm,
    required this.solvedPause,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final crop = _cropRect(image);
    final srcTile = crop.width / n;
    final cell = size.width / n;
    final blank = n * n - 1;
    final paint = Paint()..filterQuality = FilterQuality.medium;

    canvas.drawRect(
      Rect.fromLTWH(0, 0, size.width, size.height),
      Paint()..color = NunuColors.backgroundPaper.withValues(alpha: 0.72),
    );

    for (var pos = 0; pos < perm.length; pos++) {
      final tile = perm[pos];
      if (tile == blank && !solvedPause) continue;
      final src = Rect.fromLTWH(
        crop.left + (tile % n) * srcTile,
        crop.top + (tile ~/ n) * srcTile,
        srcTile,
        srcTile,
      );
      final dst = Rect.fromLTWH(
        (pos % n) * cell,
        (pos ~/ n) * cell,
        cell,
        cell,
      );
      canvas.drawImageRect(image, src, dst, paint);
    }

    if (solvedPause) {
      canvas.drawRect(
        Rect.fromLTWH(0, 0, size.width, size.height),
        Paint()
          ..color = NunuColors.successMain
          ..style = PaintingStyle.stroke
          ..strokeWidth = 6,
      );
      return;
    }

    final gridPaint = Paint()
      ..color = Colors.black.withValues(alpha: 0.55)
      ..strokeWidth = 1.5;
    for (var i = 1; i < n; i++) {
      canvas.drawLine(
        Offset(i * cell, 0),
        Offset(i * cell, size.height),
        gridPaint,
      );
      canvas.drawLine(
        Offset(0, i * cell),
        Offset(size.width, i * cell),
        gridPaint,
      );
    }
  }

  @override
  bool shouldRepaint(_PuzzlePainter old) {
    if (old.image != image || old.n != n || old.solvedPause != solvedPause) {
      return true;
    }
    for (var i = 0; i < perm.length; i++) {
      if (old.perm[i] != perm[i]) return true;
    }
    return false;
  }
}
