import 'dart:math';
import 'package:apk_arena/models/level_outcome.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../level_widget.dart';
import '../../theme/app_theme.dart';
import '../level_components/level_hud.dart';

/// Lights Out campaign: ten hardcoded stages of increasing difficulty.
///
/// The engine is generalized over four axes so each stage can twist the rules:
///   • board [size]   — 5x5 up to 7x7
///   • [holes]        — voided cells that don't exist and are skipped by taps
///   • click [pattern] — which relative cells flip on a tap (plus / X / 8-star)
///   • [colors]       — 2 (classic on/off) or 3 (Lights Out 2000, states cycle)
///
/// Every board is generated by scrambling from the solved (all-dark) state with
/// the stage's own click pattern, so it is always solvable. A generalized
/// Gaussian-elimination solver over GF(colors) computes the true optimal move
/// count of each board, which drives move-efficiency scoring.
///
/// There is deliberately no time pressure: the score depends only on how many
/// stages are cleared and how close each solve is to optimal — never on speed.
class LevelLightsOut extends LevelWidget {
  const LevelLightsOut({super.key, required super.onComplete});

  @override
  State<LevelLightsOut> createState() => _LevelLightsOutState();
}

/// Relative click patterns. Each list always includes [0,0] (the tapped cell).
const List<List<int>> _kPlus = [
  [0, 0],
  [-1, 0],
  [1, 0],
  [0, -1],
  [0, 1],
];
const List<List<int>> _kCross = [
  [0, 0],
  [-1, -1],
  [-1, 1],
  [1, -1],
  [1, 1],
];
const List<List<int>> _kStar = [
  [0, 0],
  [-1, 0],
  [1, 0],
  [0, -1],
  [0, 1],
  [-1, -1],
  [-1, 1],
  [1, -1],
  [1, 1],
];

class _StageSpec {
  final String name;
  final int size;
  final int colors;
  final List<List<int>> pattern;
  final Set<int> holes; // flattened r * size + c
  final int scramble; // number of random taps used to build the board
  final int seed;

  const _StageSpec({
    required this.name,
    required this.size,
    required this.colors,
    required this.pattern,
    required this.scramble,
    required this.seed,
    this.holes = const {},
  });
}

class _LevelLightsOutState extends State<LevelLightsOut> {
  static const List<_StageSpec> _stages = [
    _StageSpec(
      name: 'cold open',
      size: 5,
      colors: 2,
      pattern: _kPlus,
      scramble: 7,
      seed: 101,
    ),
    _StageSpec(
      name: 'wider',
      size: 6,
      colors: 2,
      pattern: _kPlus,
      scramble: 9,
      seed: 202,
    ),
    _StageSpec(
      name: 'big board',
      size: 7,
      colors: 2,
      pattern: _kPlus,
      scramble: 12,
      seed: 303,
    ),
    _StageSpec(
      name: 'swiss cheese',
      size: 5,
      colors: 2,
      pattern: _kPlus,
      holes: {6, 8, 16, 18},
      scramble: 8,
      seed: 404,
    ),
    _StageSpec(
      name: 'perforated',
      size: 6,
      colors: 2,
      pattern: _kPlus,
      holes: {14, 15, 20, 21},
      scramble: 10,
      seed: 505,
    ),
    _StageSpec(
      name: 'cross wired',
      size: 5,
      colors: 2,
      pattern: _kCross,
      scramble: 8,
      seed: 606,
    ),
    _StageSpec(
      name: 'supernova',
      size: 5,
      colors: 2,
      pattern: _kStar,
      scramble: 9,
      seed: 707,
    ),
    _StageSpec(
      name: 'technicolor',
      size: 5,
      colors: 3,
      pattern: _kPlus,
      scramble: 8,
      seed: 808,
    ),
    _StageSpec(
      name: 'prism',
      size: 6,
      colors: 3,
      pattern: _kPlus,
      scramble: 10,
      seed: 909,
    ),
    _StageSpec(
      name: 'event horizon',
      size: 6,
      colors: 3,
      pattern: _kStar,
      holes: {0, 5, 30, 35},
      scramble: 12,
      seed: 1010,
    ),
  ];

  static const int _stageCount = 10;

  // Active stage geometry / rules.
  late int _size;
  late int _colors;
  late List<List<int>> _pattern;
  late Set<int> _holes;
  late List<List<int>> _state; // per-cell state in [0, colors)

  int _stageIndex = 0;
  int _stagesCleared = 0;
  double _efficiencySum = 0; // sum of per-stage min(1, optimal/moves)

  int _stageMoves = 0;
  int _stageOptimal = 0;
  int _litCount = 0;

  int _totalMoves = 0;
  int _totalOptimal = 0;

  bool _done = false;
  bool _advancing = false;

  @override
  void initState() {
    super.initState();
    widget.registerPartialScoreGetter(_buildOutcome);
    _loadStage(0);
  }

  @override
  void dispose() {
    widget.clearPartialScoreGetter();
    super.dispose();
  }

  LevelOutcome _buildOutcome() {
    final score = (_efficiencySum / _stageCount).clamp(0.0, 1.0);
    return LevelOutcome(
      score: score,
      metrics: {
        'stages_cleared': _stagesCleared,
        'moves': _totalMoves,
        'optimal_moves': _totalOptimal,
      },
    );
  }

  bool _isActive(int r, int c) {
    if (r < 0 || r >= _size || c < 0 || c >= _size) return false;
    return !_holes.contains(r * _size + c);
  }

  int _countLit(List<List<int>> grid) {
    int n = 0;
    for (int r = 0; r < _size; r++) {
      for (int c = 0; c < _size; c++) {
        if (_isActive(r, c) && grid[r][c] != 0) n++;
      }
    }
    return n;
  }

  /// Applies one tap at (r, c) to [grid], cycling the tapped cell and its
  /// pattern-neighbours by +1 (mod colors). Skips holes / out-of-bounds.
  void _applyTap(List<List<int>> grid, int r, int c) {
    for (final d in _pattern) {
      final nr = r + d[0], nc = c + d[1];
      if (_isActive(nr, nc)) {
        grid[nr][nc] = (grid[nr][nc] + 1) % _colors;
      }
    }
  }

  void _loadStage(int index) {
    final spec = _stages[index];
    _size = spec.size;
    _colors = spec.colors;
    _pattern = spec.pattern;
    _holes = spec.holes;

    // Scramble from the solved state until we get a non-trivial, solvable
    // board. Bumping the seed keeps generation deterministic but recoverable.
    List<List<int>> chosen =
        List.generate(_size, (_) => List.filled(_size, 0));
    int optimal = 0;
    for (int attempt = 0; attempt < 64; attempt++) {
      final rng = Random(spec.seed + attempt);
      final grid = List.generate(_size, (_) => List.filled(_size, 0));
      final active = <int>[
        for (int r = 0; r < _size; r++)
          for (int c = 0; c < _size; c++)
            if (_isActive(r, c)) r * _size + c,
      ];
      for (int i = 0; i < spec.scramble; i++) {
        final cell = active[rng.nextInt(active.length)];
        _applyTap(grid, cell ~/ _size, cell % _size);
      }
      if (_countLit(grid) == 0) continue;
      final opt = _optimalMoves(grid);
      if (opt == null || opt == 0) continue;
      chosen = grid;
      optimal = opt;
      break;
    }

    _state = chosen;
    _stageOptimal = optimal;
    _stageMoves = 0;
    _litCount = _countLit(chosen);
  }

  void _onTap(int r, int c) {
    if (_done || _advancing || !_isActive(r, c)) return;
    setState(() {
      _applyTap(_state, r, c);
      _stageMoves++;
      _totalMoves++;
      _litCount = _countLit(_state);
      HapticFeedback.lightImpact();
      if (_litCount == 0) _onStageCleared();
    });
  }

  void _resetStage() {
    if (_done || _advancing) return;
    setState(() {
      _totalMoves -= _stageMoves; // undo this stage's contribution
      _loadStage(_stageIndex);
    });
    HapticFeedback.selectionClick();
  }

  void _onStageCleared() {
    _stagesCleared++;
    _totalOptimal += _stageOptimal;
    final eff = _stageMoves <= 0
        ? 1.0
        : (_stageOptimal / _stageMoves).clamp(0.0, 1.0);
    _efficiencySum += eff;
    HapticFeedback.mediumImpact();

    if (_stageIndex >= _stageCount - 1) {
      _finish();
      return;
    }

    _advancing = true;
    Future.delayed(const Duration(milliseconds: 550), () {
      if (!mounted || _done) return;
      setState(() {
        _stageIndex++;
        _loadStage(_stageIndex);
        _advancing = false;
      });
    });
  }

  void _finish() {
    if (_done) return;
    _done = true;
    HapticFeedback.mediumImpact();
    Future.delayed(const Duration(milliseconds: 600), () {
      if (!mounted) return;
      widget.onComplete(_buildOutcome());
    });
  }

  // ---------------------------------------------------------------------------
  // Solver: minimum number of taps to clear [grid], over GF(colors).
  // Returns null if (unexpectedly) inconsistent.
  // ---------------------------------------------------------------------------

  int? _optimalMoves(List<List<int>> grid) {
    final p = _colors;
    final active = <int>[
      for (int r = 0; r < _size; r++)
        for (int c = 0; c < _size; c++)
          if (_isActive(r, c)) r * _size + c,
    ];
    final n = active.length;
    final varOf = <int, int>{for (int i = 0; i < n; i++) active[i]: i};

    // aug[row][col] = effect on active cell `row` of tapping active cell `col`;
    // last column is the target state to cancel.
    final aug = List.generate(n, (_) => List.filled(n + 1, 0));
    for (int j = 0; j < n; j++) {
      final cell = active[j];
      final jr = cell ~/ _size, jc = cell % _size;
      for (final d in _pattern) {
        final nr = jr + d[0], nc = jc + d[1];
        if (!_isActive(nr, nc)) continue;
        final i = varOf[nr * _size + nc]!;
        aug[i][j] = (aug[i][j] + 1) % p;
      }
    }
    for (int i = 0; i < n; i++) {
      final cell = active[i];
      // Taps *add* to each cell, so to reach 0 we must cancel the current
      // state: solve for an effect of -state (mod p). For p=2 this equals the
      // state itself, but for 3-color boards the negation matters.
      final state = grid[cell ~/ _size][cell % _size] % p;
      aug[i][n] = (p - state) % p;
    }

    final pivotCol = List.filled(n, -1);
    int rank = 0;
    for (int col = 0; col < n && rank < n; col++) {
      int pivotRow = -1;
      for (int row = rank; row < n; row++) {
        if (aug[row][col] != 0) {
          pivotRow = row;
          break;
        }
      }
      if (pivotRow == -1) continue;
      final tmp = aug[rank];
      aug[rank] = aug[pivotRow];
      aug[pivotRow] = tmp;
      final inv = _modInverse(aug[rank][col], p);
      for (int k = col; k <= n; k++) {
        aug[rank][k] = (aug[rank][k] * inv) % p;
      }
      for (int row = 0; row < n; row++) {
        if (row == rank) continue;
        final f = aug[row][col];
        if (f == 0) continue;
        for (int k = col; k <= n; k++) {
          aug[row][k] = (aug[row][k] - f * aug[rank][k]) % p;
          if (aug[row][k] < 0) aug[row][k] += p;
        }
      }
      pivotCol[rank] = col;
      rank++;
    }

    // Consistency check: a zero row with nonzero rhs means no solution.
    for (int row = rank; row < n; row++) {
      if (aug[row][n] != 0) return null;
    }

    final particular = List.filled(n, 0);
    for (int i = 0; i < rank; i++) {
      if (pivotCol[i] != -1) particular[pivotCol[i]] = aug[i][n];
    }

    final pivotSet = {for (int i = 0; i < rank; i++) pivotCol[i]};
    final freeVars = [
      for (int c = 0; c < n; c++)
        if (!pivotSet.contains(c)) c,
    ];

    int weight(List<int> v) => v.fold(0, (a, b) => a + b);

    // No free variables → unique solution.
    if (freeVars.isEmpty) return weight(particular);

    // Null-space basis: one vector per free variable.
    final nullBasis = <List<int>>[];
    for (final fv in freeVars) {
      final v = List.filled(n, 0);
      v[fv] = 1;
      for (int i = 0; i < rank; i++) {
        if (pivotCol[i] != -1 && aug[i][fv] != 0) {
          v[pivotCol[i]] = (p - aug[i][fv]) % p;
        }
      }
      nullBasis.add(v);
    }

    // Search null-space combinations for the lightest solution. Bounded so a
    // pathological board can never hang the UI; falls back to the particular
    // solution if the space is too large to enumerate.
    final nullity = freeVars.length;
    int combos = 1;
    for (int i = 0; i < nullity; i++) {
      combos *= p;
      if (combos > 300000) return weight(particular);
    }

    int best = weight(particular);
    final coeff = List.filled(nullity, 0);
    for (int mask = 1; mask < combos; mask++) {
      // Advance the mixed-radix (base p) counter.
      int carry = 1;
      for (int i = 0; i < nullity && carry > 0; i++) {
        coeff[i] += carry;
        if (coeff[i] >= p) {
          coeff[i] = 0;
        } else {
          carry = 0;
        }
      }
      final candidate = List.of(particular);
      for (int k = 0; k < nullity; k++) {
        final ck = coeff[k];
        if (ck == 0) continue;
        for (int i = 0; i < n; i++) {
          candidate[i] = (candidate[i] + ck * nullBasis[k][i]) % p;
        }
      }
      final w = weight(candidate);
      if (w < best) best = w;
    }
    return best;
  }

  int _modInverse(int a, int p) {
    a %= p;
    for (int x = 1; x < p; x++) {
      if ((a * x) % p == 1) return x;
    }
    return 1; // p is prime here (2 or 3), so this is unreachable for a != 0
  }

  // ---------------------------------------------------------------------------
  // UI
  // ---------------------------------------------------------------------------

  @override
  Widget build(BuildContext context) {
    final spec = _stages[_stageIndex];
    return Container(
      color: const Color(0xFF050510),
      child: SafeArea(
        child: Column(
          children: [
            LevelHud(
              stageText: '${_stageIndex + 1}/$_stageCount',
              trailing: Text(
                'moves $_stageMoves',
                style: const TextStyle(
                  color: NunuColors.textSecondary,
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                ),
              ),
              infoTitle: 'blackout',
              infoItems: const [
                LevelHudBullet('💡', 'tap a cell to advance it and its neighbours'),
                LevelHudBullet('🎯', 'turn every cell dark to clear the board'),
                LevelHudBullet('🌀', 'later boards change size, add holes, shift which neighbours flip, and cycle through colors'),
                LevelHudBullet('⭐', 'fewer moves = better score; take all the time you need'),
              ],
            ),
            Padding(
              padding: const EdgeInsets.only(top: 12),
              child: Text(
                '${spec.name}  ·  lit $_litCount',
                style: TextStyle(
                  color: _litCount == 0
                      ? NunuColors.successMain
                      : NunuColors.warningMain,
                  fontSize: 14,
                  fontWeight: FontWeight.w800,
                ),
              ),
            ),
            Expanded(child: Center(child: _buildGrid())),
            _buildControls(),
            const SizedBox(height: 8),
          ],
        ),
      ),
    );
  }

  Widget _buildControls() {
    return TextButton.icon(
      onPressed: _resetStage,
      icon: const Icon(Icons.refresh, size: 18, color: NunuColors.textSecondary),
      label: const Text(
        'reset board',
        style: TextStyle(
          color: NunuColors.textSecondary,
          fontSize: 13,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
  }

  Widget _buildGrid() {
    return LayoutBuilder(
      builder: (context, constraints) {
        final cellSize = min(
          (constraints.maxWidth - 48) / _size,
          (constraints.maxHeight - 16) / _size,
        );
        return SizedBox(
          width: cellSize * _size + 16,
          height: cellSize * _size + 16,
          child: GridView.builder(
            physics: const NeverScrollableScrollPhysics(),
            padding: const EdgeInsets.all(8),
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: _size,
              mainAxisSpacing: 6,
              crossAxisSpacing: 6,
            ),
            itemCount: _size * _size,
            itemBuilder: (_, i) => _buildCell(i ~/ _size, i % _size, cellSize),
          ),
        );
      },
    );
  }

  /// Color for a given cell state. State 0 is "dark/off"; higher states are
  /// distinct lit colors (used by the 3-color boards).
  Color _stateColor(int s) {
    switch (s) {
      case 1:
        return NunuColors.warningMain; // amber
      case 2:
        return const Color(0xFF22D3EE); // cyan
      default:
        return const Color(0xFF1A1A2E); // off
    }
  }

  Widget _buildCell(int r, int c, double size) {
    if (!_isActive(r, c)) {
      // A hole: render as empty void, not tappable.
      return const SizedBox.shrink();
    }
    final s = _state[r][c];
    final lit = s != 0;
    final color = _stateColor(s);

    return GestureDetector(
      onTap: () => _onTap(r, c),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
            color: lit
                ? color.withOpacity(0.7)
                : NunuColors.primaryDark.withOpacity(0.3),
            width: 2,
          ),
          boxShadow: lit
              ? [
                  BoxShadow(
                    color: color.withOpacity(0.6),
                    blurRadius: 16,
                    spreadRadius: 2,
                  ),
                ]
              : null,
        ),
        child: Center(
          child: Icon(
            lit ? Icons.lightbulb : Icons.lightbulb_outline,
            color: lit ? Colors.white : Colors.white.withOpacity(0.2),
            size: size * 0.35,
          ),
        ),
      ),
    );
  }
}
